name: Release

on: push
#   repository_dispatch:
#   push:
#     tags:
#       - v* #当有v开头的tag push时触发event

env:
  CARGO_TERM_COLOR: always #https://doc.rust-lang.org/cargo/reference/config.html#termcolor

jobs:

  publish-to-github:
    name: Publish to Github
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
        - build: x86
          os: ubuntu-latest
          rust: stable
          target: i686-linux-android
          linker: i686-linux-android29-clang
          cross: true
        - build: x86_64
          os: ubuntu-latest
          rust: stable
          target: x86_64-linux-android
          linker: x86_64-linux-android29-clang
          cross: true
        - build: arm-v7
          os: ubuntu-latest
          rust: stable
          target: armv7-linux-androideabi
          linker: armv7a-linux-androideabi29-clang
          cross: true
        - build: aarch64
          os: ubuntu-latest
          rust: stable
          target: aarch64-linux-android
          linker: aarch64-linux-android29-clang
          cross: true
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Cache #缓存依赖关系和输出已改善执行时间
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.rustup
          target
        key: ${{ runner.os }}-${{ matrix.rust }}

    - name: Install Linker
      if: matrix.cross
      run: |
        sudo apt update
        sudo apt install ${{ matrix.linker }}

    - name: Install Rust
      run: |
        rustup install ${{ matrix.rust }}
        rustup target add ${{ matrix.target }}
        rustup show
    - name: Install libusb
      run: | 
        sudo apt-get install libusb-dev
        sudo apt-get install libusb-1.0-0-dev 

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
