name: Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

#     runs-on: ubuntu-latest
    runs-on: macos-12

    steps:
#     - uses: actions/checkout@v3
#     - name: Install opssl
#       run: |
#         openssl version
#        sudo apt-get install openssl
#        sudo apt-get install libssl-dev
#        echo $OPENSSL_INCLUDE_DIR
#        echo $OPENSSL_INCLUDE_DIR2
#        ls /usr/local/
#        env
        
    
#     - uses: actions/checkout@v3
#     - name: Install latest nightly
#       uses: actions-rs/toolchain@v1
#       with:
#           toolchain: nightly
#           override: true
#           target: aarch64-linux-android, armv7-linux-androideabi, i686-linux-android, x86_64-linux-android
#     - run: | 
#           rustup show 

#     - uses: nttld/setup-ndk@v1.2.0
#       id: setup-ndk
#       with:
#         ndk-version: r22b
#         add-to-path: true
#         local-cache: false
      
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2.0.6
    
    - run: | 
          echo 11111
          ls /Users/runner/Library/Android/sdk/ndk
          echo 22222
          ls -a ~/
          ls /opt/
          echo $ANDROID_NDK_HOME
          ls $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64/bin
          echo aaaaaaaaaaaaa

      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
