name: Test

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: macos-12

    steps:
#     - uses: actions/checkout@v3
    - name: Install opssl
      run: |
        pwd
        echo aaa
        ls
        echo ${{ github.ref }}
