name: Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install opssl
      run: |
        export OPENSSL_INCLUDE_DIR='sudo apt-get install openssl'/include
        export OPENSSL_INCLUDE_DIR2='sudo apt-get install libssl-dev'/lib
        echo $OPENSSL_INCLUDE_DIR
        echo $OPENSSL_INCLUDE_DIR2
        env
        
    - name: list_command
      run: ls ${{github.workspace}}
#     - run: ls /opt/
